extern int _putchar(char c);
extern void print_alphabet(void);
extern void print_alphabet_x10(void);
extern int _islower(int c);
extern int _isalpha(int c);
extern int print_sign(int n);
extern int _abs(int);
extern int print_last_digit(int);
extern void printminutes(int x1, int x2, int y1, int y2);
extern void jack_bauer(void);
