int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
void times_table(void);
int add(int, int);
int print_last_digit(int);
void printminutes(int x1, int x2, int y1, int y2);
void jack_bauer(void);
